/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"
	json "encoding/json"
	fmt "fmt"

	v1alpha1 "k8s.io/api/rbac/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rbacv1alpha1 "k8s.io/client-go/applyconfigurations/rbac/v1alpha1"
	testing "k8s.io/client-go/testing"
)

// FakeConditionalClusterRoleBindings implements ConditionalClusterRoleBindingInterface
type FakeConditionalClusterRoleBindings struct {
	Fake *FakeRbacV1alpha1
}

var conditionalclusterrolebindingsResource = v1alpha1.SchemeGroupVersion.WithResource("conditionalclusterrolebindings")

var conditionalclusterrolebindingsKind = v1alpha1.SchemeGroupVersion.WithKind("ConditionalClusterRoleBinding")

// Get takes name of the conditionalClusterRoleBinding, and returns the corresponding conditionalClusterRoleBinding object, and an error if there is any.
func (c *FakeConditionalClusterRoleBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConditionalClusterRoleBinding, err error) {
	emptyResult := &v1alpha1.ConditionalClusterRoleBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(conditionalclusterrolebindingsResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ConditionalClusterRoleBinding), err
}

// List takes label and field selectors, and returns the list of ConditionalClusterRoleBindings that match those selectors.
func (c *FakeConditionalClusterRoleBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConditionalClusterRoleBindingList, err error) {
	emptyResult := &v1alpha1.ConditionalClusterRoleBindingList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(conditionalclusterrolebindingsResource, conditionalclusterrolebindingsKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConditionalClusterRoleBindingList{ListMeta: obj.(*v1alpha1.ConditionalClusterRoleBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConditionalClusterRoleBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested conditionalClusterRoleBindings.
func (c *FakeConditionalClusterRoleBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(conditionalclusterrolebindingsResource, opts))
}

// Create takes the representation of a conditionalClusterRoleBinding and creates it.  Returns the server's representation of the conditionalClusterRoleBinding, and an error, if there is any.
func (c *FakeConditionalClusterRoleBindings) Create(ctx context.Context, conditionalClusterRoleBinding *v1alpha1.ConditionalClusterRoleBinding, opts v1.CreateOptions) (result *v1alpha1.ConditionalClusterRoleBinding, err error) {
	emptyResult := &v1alpha1.ConditionalClusterRoleBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(conditionalclusterrolebindingsResource, conditionalClusterRoleBinding, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ConditionalClusterRoleBinding), err
}

// Update takes the representation of a conditionalClusterRoleBinding and updates it. Returns the server's representation of the conditionalClusterRoleBinding, and an error, if there is any.
func (c *FakeConditionalClusterRoleBindings) Update(ctx context.Context, conditionalClusterRoleBinding *v1alpha1.ConditionalClusterRoleBinding, opts v1.UpdateOptions) (result *v1alpha1.ConditionalClusterRoleBinding, err error) {
	emptyResult := &v1alpha1.ConditionalClusterRoleBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(conditionalclusterrolebindingsResource, conditionalClusterRoleBinding, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ConditionalClusterRoleBinding), err
}

// Delete takes name of the conditionalClusterRoleBinding and deletes it. Returns an error if one occurs.
func (c *FakeConditionalClusterRoleBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(conditionalclusterrolebindingsResource, name, opts), &v1alpha1.ConditionalClusterRoleBinding{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConditionalClusterRoleBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(conditionalclusterrolebindingsResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConditionalClusterRoleBindingList{})
	return err
}

// Patch applies the patch and returns the patched conditionalClusterRoleBinding.
func (c *FakeConditionalClusterRoleBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConditionalClusterRoleBinding, err error) {
	emptyResult := &v1alpha1.ConditionalClusterRoleBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(conditionalclusterrolebindingsResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ConditionalClusterRoleBinding), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied conditionalClusterRoleBinding.
func (c *FakeConditionalClusterRoleBindings) Apply(ctx context.Context, conditionalClusterRoleBinding *rbacv1alpha1.ConditionalClusterRoleBindingApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ConditionalClusterRoleBinding, err error) {
	if conditionalClusterRoleBinding == nil {
		return nil, fmt.Errorf("conditionalClusterRoleBinding provided to Apply must not be nil")
	}
	data, err := json.Marshal(conditionalClusterRoleBinding)
	if err != nil {
		return nil, err
	}
	name := conditionalClusterRoleBinding.Name
	if name == nil {
		return nil, fmt.Errorf("conditionalClusterRoleBinding.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.ConditionalClusterRoleBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(conditionalclusterrolebindingsResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ConditionalClusterRoleBinding), err
}
