// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.11.2
// source: plugin.proto

package plugin

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdmissionReview []byte `protobuf:"bytes,1,opt,name=admissionReview,proto3" json:"admissionReview,omitempty"`
}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ValidateRequest) GetAdmissionReview() []byte {
	if x != nil {
		return x.AdmissionReview
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdmissionReview []byte `protobuf:"bytes,1,opt,name=admissionReview,proto3" json:"admissionReview,omitempty"`
}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ValidateResponse) GetAdmissionReview() []byte {
	if x != nil {
		return x.AdmissionReview
	}
	return nil
}

// go:plugin type=plugin version=1
type Validation interface {
	Validate(context.Context, ValidateRequest) (ValidateResponse, error)
}
