// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.11.2
// source: plugin.proto

package plugin

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdmissionReview []byte `protobuf:"bytes,1,opt,name=admissionReview,proto3" json:"admissionReview,omitempty"`
}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ValidateRequest) GetAdmissionReview() []byte {
	if x != nil {
		return x.AdmissionReview
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdmissionReview []byte `protobuf:"bytes,1,opt,name=admissionReview,proto3" json:"admissionReview,omitempty"`
}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ValidateResponse) GetAdmissionReview() []byte {
	if x != nil {
		return x.AdmissionReview
	}
	return nil
}

// TODO this should look like SubjectAccessReviewSpec
type SubjectAccessReviewSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Groups   []string `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	Verb     string   `protobuf:"bytes,3,opt,name=verb,proto3" json:"verb,omitempty"`
	Resource string   `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *SubjectAccessReviewSpec) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SubjectAccessReviewSpec) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SubjectAccessReviewSpec) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *SubjectAccessReviewSpec) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *SubjectAccessReviewSpec) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type SubjectAccessReviewStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *SubjectAccessReviewStatus) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SubjectAccessReviewStatus) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *SubjectAccessReviewStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InformerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group     string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Resource  string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InformerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *InformerRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *InformerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InformerRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *InformerRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InformerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InformerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace         string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name              string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResourceVersion   string            `protobuf:"bytes,3,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	CreationTimestamp string            `protobuf:"bytes,4,opt,name=creationTimestamp,proto3" json:"creationTimestamp,omitempty"`
	Labels            map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *InformerResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *InformerResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InformerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InformerResponse) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *InformerResponse) GetCreationTimestamp() string {
	if x != nil {
		return x.CreationTimestamp
	}
	return ""
}

func (x *InformerResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// go:plugin type=plugin version=1
type Validation interface {
	Validate(context.Context, ValidateRequest) (ValidateResponse, error)
}

// go:plugin type=host version=1
type Host interface {
	Authorizer(context.Context, SubjectAccessReviewSpec) (SubjectAccessReviewStatus, error)
	Informer(context.Context, InformerRequest) (InformerResponse, error)
}
