// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha1 "k8s.io/api/authentication/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	authentication "k8s.io/kubernetes/pkg/apis/authentication"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AuthenticationConfig)(nil), (*authentication.AuthenticationConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationConfig_To_authentication_AuthenticationConfig(a.(*v1alpha1.AuthenticationConfig), b.(*authentication.AuthenticationConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.AuthenticationConfig)(nil), (*v1alpha1.AuthenticationConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_AuthenticationConfig_To_v1alpha1_AuthenticationConfig(a.(*authentication.AuthenticationConfig), b.(*v1alpha1.AuthenticationConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AuthenticationConfigList)(nil), (*authentication.AuthenticationConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationConfigList_To_authentication_AuthenticationConfigList(a.(*v1alpha1.AuthenticationConfigList), b.(*authentication.AuthenticationConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.AuthenticationConfigList)(nil), (*v1alpha1.AuthenticationConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_AuthenticationConfigList_To_v1alpha1_AuthenticationConfigList(a.(*authentication.AuthenticationConfigList), b.(*v1alpha1.AuthenticationConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AuthenticationConfigSpec)(nil), (*authentication.AuthenticationConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationConfigSpec_To_authentication_AuthenticationConfigSpec(a.(*v1alpha1.AuthenticationConfigSpec), b.(*authentication.AuthenticationConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.AuthenticationConfigSpec)(nil), (*v1alpha1.AuthenticationConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_AuthenticationConfigSpec_To_v1alpha1_AuthenticationConfigSpec(a.(*authentication.AuthenticationConfigSpec), b.(*v1alpha1.AuthenticationConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AuthenticationConfigStatus)(nil), (*authentication.AuthenticationConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationConfigStatus_To_authentication_AuthenticationConfigStatus(a.(*v1alpha1.AuthenticationConfigStatus), b.(*authentication.AuthenticationConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.AuthenticationConfigStatus)(nil), (*v1alpha1.AuthenticationConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_AuthenticationConfigStatus_To_v1alpha1_AuthenticationConfigStatus(a.(*authentication.AuthenticationConfigStatus), b.(*v1alpha1.AuthenticationConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.OIDCConfig)(nil), (*authentication.OIDCConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OIDCConfig_To_authentication_OIDCConfig(a.(*v1alpha1.OIDCConfig), b.(*authentication.OIDCConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.OIDCConfig)(nil), (*v1alpha1.OIDCConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_OIDCConfig_To_v1alpha1_OIDCConfig(a.(*authentication.OIDCConfig), b.(*v1alpha1.OIDCConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServerAuthentication)(nil), (*authentication.ServerAuthentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServerAuthentication_To_authentication_ServerAuthentication(a.(*v1alpha1.ServerAuthentication), b.(*authentication.ServerAuthentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.ServerAuthentication)(nil), (*v1alpha1.ServerAuthentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_ServerAuthentication_To_v1alpha1_ServerAuthentication(a.(*authentication.ServerAuthentication), b.(*v1alpha1.ServerAuthentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServiceReference)(nil), (*authentication.ServiceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceReference_To_authentication_ServiceReference(a.(*v1alpha1.ServiceReference), b.(*authentication.ServiceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.ServiceReference)(nil), (*v1alpha1.ServiceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_ServiceReference_To_v1alpha1_ServiceReference(a.(*authentication.ServiceReference), b.(*v1alpha1.ServiceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.WebhookClientConfig)(nil), (*authentication.WebhookClientConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WebhookClientConfig_To_authentication_WebhookClientConfig(a.(*v1alpha1.WebhookClientConfig), b.(*authentication.WebhookClientConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.WebhookClientConfig)(nil), (*v1alpha1.WebhookClientConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_WebhookClientConfig_To_v1alpha1_WebhookClientConfig(a.(*authentication.WebhookClientConfig), b.(*v1alpha1.WebhookClientConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.WebhookConfig)(nil), (*authentication.WebhookConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WebhookConfig_To_authentication_WebhookConfig(a.(*v1alpha1.WebhookConfig), b.(*authentication.WebhookConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.WebhookConfig)(nil), (*v1alpha1.WebhookConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_WebhookConfig_To_v1alpha1_WebhookConfig(a.(*authentication.WebhookConfig), b.(*v1alpha1.WebhookConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.X509Config)(nil), (*authentication.X509Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_X509Config_To_authentication_X509Config(a.(*v1alpha1.X509Config), b.(*authentication.X509Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.X509Config)(nil), (*v1alpha1.X509Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_X509Config_To_v1alpha1_X509Config(a.(*authentication.X509Config), b.(*v1alpha1.X509Config), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AuthenticationConfig_To_authentication_AuthenticationConfig(in *v1alpha1.AuthenticationConfig, out *authentication.AuthenticationConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_AuthenticationConfigSpec_To_authentication_AuthenticationConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AuthenticationConfigStatus_To_authentication_AuthenticationConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AuthenticationConfig_To_authentication_AuthenticationConfig is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationConfig_To_authentication_AuthenticationConfig(in *v1alpha1.AuthenticationConfig, out *authentication.AuthenticationConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationConfig_To_authentication_AuthenticationConfig(in, out, s)
}

func autoConvert_authentication_AuthenticationConfig_To_v1alpha1_AuthenticationConfig(in *authentication.AuthenticationConfig, out *v1alpha1.AuthenticationConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_authentication_AuthenticationConfigSpec_To_v1alpha1_AuthenticationConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_authentication_AuthenticationConfigStatus_To_v1alpha1_AuthenticationConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_authentication_AuthenticationConfig_To_v1alpha1_AuthenticationConfig is an autogenerated conversion function.
func Convert_authentication_AuthenticationConfig_To_v1alpha1_AuthenticationConfig(in *authentication.AuthenticationConfig, out *v1alpha1.AuthenticationConfig, s conversion.Scope) error {
	return autoConvert_authentication_AuthenticationConfig_To_v1alpha1_AuthenticationConfig(in, out, s)
}

func autoConvert_v1alpha1_AuthenticationConfigList_To_authentication_AuthenticationConfigList(in *v1alpha1.AuthenticationConfigList, out *authentication.AuthenticationConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]authentication.AuthenticationConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_AuthenticationConfigList_To_authentication_AuthenticationConfigList is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationConfigList_To_authentication_AuthenticationConfigList(in *v1alpha1.AuthenticationConfigList, out *authentication.AuthenticationConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationConfigList_To_authentication_AuthenticationConfigList(in, out, s)
}

func autoConvert_authentication_AuthenticationConfigList_To_v1alpha1_AuthenticationConfigList(in *authentication.AuthenticationConfigList, out *v1alpha1.AuthenticationConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.AuthenticationConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_authentication_AuthenticationConfigList_To_v1alpha1_AuthenticationConfigList is an autogenerated conversion function.
func Convert_authentication_AuthenticationConfigList_To_v1alpha1_AuthenticationConfigList(in *authentication.AuthenticationConfigList, out *v1alpha1.AuthenticationConfigList, s conversion.Scope) error {
	return autoConvert_authentication_AuthenticationConfigList_To_v1alpha1_AuthenticationConfigList(in, out, s)
}

func autoConvert_v1alpha1_AuthenticationConfigSpec_To_authentication_AuthenticationConfigSpec(in *v1alpha1.AuthenticationConfigSpec, out *authentication.AuthenticationConfigSpec, s conversion.Scope) error {
	out.Type = authentication.AuthenticationConfigType(in.Type)
	out.X509 = (*authentication.X509Config)(unsafe.Pointer(in.X509))
	out.OIDC = (*authentication.OIDCConfig)(unsafe.Pointer(in.OIDC))
	out.Webhook = (*authentication.WebhookConfig)(unsafe.Pointer(in.Webhook))
	out.ServerAuthentication = (*authentication.ServerAuthentication)(unsafe.Pointer(in.ServerAuthentication))
	if err := Convert_v1alpha1_WebhookClientConfig_To_authentication_WebhookClientConfig(&in.ClientConfig, &out.ClientConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AuthenticationConfigSpec_To_authentication_AuthenticationConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationConfigSpec_To_authentication_AuthenticationConfigSpec(in *v1alpha1.AuthenticationConfigSpec, out *authentication.AuthenticationConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationConfigSpec_To_authentication_AuthenticationConfigSpec(in, out, s)
}

func autoConvert_authentication_AuthenticationConfigSpec_To_v1alpha1_AuthenticationConfigSpec(in *authentication.AuthenticationConfigSpec, out *v1alpha1.AuthenticationConfigSpec, s conversion.Scope) error {
	out.Type = v1alpha1.AuthenticationConfigType(in.Type)
	out.X509 = (*v1alpha1.X509Config)(unsafe.Pointer(in.X509))
	out.OIDC = (*v1alpha1.OIDCConfig)(unsafe.Pointer(in.OIDC))
	out.Webhook = (*v1alpha1.WebhookConfig)(unsafe.Pointer(in.Webhook))
	out.ServerAuthentication = (*v1alpha1.ServerAuthentication)(unsafe.Pointer(in.ServerAuthentication))
	if err := Convert_authentication_WebhookClientConfig_To_v1alpha1_WebhookClientConfig(&in.ClientConfig, &out.ClientConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_authentication_AuthenticationConfigSpec_To_v1alpha1_AuthenticationConfigSpec is an autogenerated conversion function.
func Convert_authentication_AuthenticationConfigSpec_To_v1alpha1_AuthenticationConfigSpec(in *authentication.AuthenticationConfigSpec, out *v1alpha1.AuthenticationConfigSpec, s conversion.Scope) error {
	return autoConvert_authentication_AuthenticationConfigSpec_To_v1alpha1_AuthenticationConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_AuthenticationConfigStatus_To_authentication_AuthenticationConfigStatus(in *v1alpha1.AuthenticationConfigStatus, out *authentication.AuthenticationConfigStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_AuthenticationConfigStatus_To_authentication_AuthenticationConfigStatus is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationConfigStatus_To_authentication_AuthenticationConfigStatus(in *v1alpha1.AuthenticationConfigStatus, out *authentication.AuthenticationConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationConfigStatus_To_authentication_AuthenticationConfigStatus(in, out, s)
}

func autoConvert_authentication_AuthenticationConfigStatus_To_v1alpha1_AuthenticationConfigStatus(in *authentication.AuthenticationConfigStatus, out *v1alpha1.AuthenticationConfigStatus, s conversion.Scope) error {
	return nil
}

// Convert_authentication_AuthenticationConfigStatus_To_v1alpha1_AuthenticationConfigStatus is an autogenerated conversion function.
func Convert_authentication_AuthenticationConfigStatus_To_v1alpha1_AuthenticationConfigStatus(in *authentication.AuthenticationConfigStatus, out *v1alpha1.AuthenticationConfigStatus, s conversion.Scope) error {
	return autoConvert_authentication_AuthenticationConfigStatus_To_v1alpha1_AuthenticationConfigStatus(in, out, s)
}

func autoConvert_v1alpha1_OIDCConfig_To_authentication_OIDCConfig(in *v1alpha1.OIDCConfig, out *authentication.OIDCConfig, s conversion.Scope) error {
	out.Issuer = in.Issuer
	out.ClientID = in.ClientID
	out.UsernameClaim = in.UsernameClaim
	return nil
}

// Convert_v1alpha1_OIDCConfig_To_authentication_OIDCConfig is an autogenerated conversion function.
func Convert_v1alpha1_OIDCConfig_To_authentication_OIDCConfig(in *v1alpha1.OIDCConfig, out *authentication.OIDCConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_OIDCConfig_To_authentication_OIDCConfig(in, out, s)
}

func autoConvert_authentication_OIDCConfig_To_v1alpha1_OIDCConfig(in *authentication.OIDCConfig, out *v1alpha1.OIDCConfig, s conversion.Scope) error {
	out.Issuer = in.Issuer
	out.ClientID = in.ClientID
	out.UsernameClaim = in.UsernameClaim
	return nil
}

// Convert_authentication_OIDCConfig_To_v1alpha1_OIDCConfig is an autogenerated conversion function.
func Convert_authentication_OIDCConfig_To_v1alpha1_OIDCConfig(in *authentication.OIDCConfig, out *v1alpha1.OIDCConfig, s conversion.Scope) error {
	return autoConvert_authentication_OIDCConfig_To_v1alpha1_OIDCConfig(in, out, s)
}

func autoConvert_v1alpha1_ServerAuthentication_To_authentication_ServerAuthentication(in *v1alpha1.ServerAuthentication, out *authentication.ServerAuthentication, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ServerAuthentication_To_authentication_ServerAuthentication is an autogenerated conversion function.
func Convert_v1alpha1_ServerAuthentication_To_authentication_ServerAuthentication(in *v1alpha1.ServerAuthentication, out *authentication.ServerAuthentication, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServerAuthentication_To_authentication_ServerAuthentication(in, out, s)
}

func autoConvert_authentication_ServerAuthentication_To_v1alpha1_ServerAuthentication(in *authentication.ServerAuthentication, out *v1alpha1.ServerAuthentication, s conversion.Scope) error {
	return nil
}

// Convert_authentication_ServerAuthentication_To_v1alpha1_ServerAuthentication is an autogenerated conversion function.
func Convert_authentication_ServerAuthentication_To_v1alpha1_ServerAuthentication(in *authentication.ServerAuthentication, out *v1alpha1.ServerAuthentication, s conversion.Scope) error {
	return autoConvert_authentication_ServerAuthentication_To_v1alpha1_ServerAuthentication(in, out, s)
}

func autoConvert_v1alpha1_ServiceReference_To_authentication_ServiceReference(in *v1alpha1.ServiceReference, out *authentication.ServiceReference, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Path = (*string)(unsafe.Pointer(in.Path))
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	return nil
}

// Convert_v1alpha1_ServiceReference_To_authentication_ServiceReference is an autogenerated conversion function.
func Convert_v1alpha1_ServiceReference_To_authentication_ServiceReference(in *v1alpha1.ServiceReference, out *authentication.ServiceReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceReference_To_authentication_ServiceReference(in, out, s)
}

func autoConvert_authentication_ServiceReference_To_v1alpha1_ServiceReference(in *authentication.ServiceReference, out *v1alpha1.ServiceReference, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Path = (*string)(unsafe.Pointer(in.Path))
	out.Port = (*int32)(unsafe.Pointer(in.Port))
	return nil
}

// Convert_authentication_ServiceReference_To_v1alpha1_ServiceReference is an autogenerated conversion function.
func Convert_authentication_ServiceReference_To_v1alpha1_ServiceReference(in *authentication.ServiceReference, out *v1alpha1.ServiceReference, s conversion.Scope) error {
	return autoConvert_authentication_ServiceReference_To_v1alpha1_ServiceReference(in, out, s)
}

func autoConvert_v1alpha1_WebhookClientConfig_To_authentication_WebhookClientConfig(in *v1alpha1.WebhookClientConfig, out *authentication.WebhookClientConfig, s conversion.Scope) error {
	out.URL = (*string)(unsafe.Pointer(in.URL))
	out.Service = (*authentication.ServiceReference)(unsafe.Pointer(in.Service))
	out.CABundle = *(*[]byte)(unsafe.Pointer(&in.CABundle))
	return nil
}

// Convert_v1alpha1_WebhookClientConfig_To_authentication_WebhookClientConfig is an autogenerated conversion function.
func Convert_v1alpha1_WebhookClientConfig_To_authentication_WebhookClientConfig(in *v1alpha1.WebhookClientConfig, out *authentication.WebhookClientConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WebhookClientConfig_To_authentication_WebhookClientConfig(in, out, s)
}

func autoConvert_authentication_WebhookClientConfig_To_v1alpha1_WebhookClientConfig(in *authentication.WebhookClientConfig, out *v1alpha1.WebhookClientConfig, s conversion.Scope) error {
	out.URL = (*string)(unsafe.Pointer(in.URL))
	out.Service = (*v1alpha1.ServiceReference)(unsafe.Pointer(in.Service))
	out.CABundle = *(*[]byte)(unsafe.Pointer(&in.CABundle))
	return nil
}

// Convert_authentication_WebhookClientConfig_To_v1alpha1_WebhookClientConfig is an autogenerated conversion function.
func Convert_authentication_WebhookClientConfig_To_v1alpha1_WebhookClientConfig(in *authentication.WebhookClientConfig, out *v1alpha1.WebhookClientConfig, s conversion.Scope) error {
	return autoConvert_authentication_WebhookClientConfig_To_v1alpha1_WebhookClientConfig(in, out, s)
}

func autoConvert_v1alpha1_WebhookConfig_To_authentication_WebhookConfig(in *v1alpha1.WebhookConfig, out *authentication.WebhookConfig, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_WebhookConfig_To_authentication_WebhookConfig is an autogenerated conversion function.
func Convert_v1alpha1_WebhookConfig_To_authentication_WebhookConfig(in *v1alpha1.WebhookConfig, out *authentication.WebhookConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WebhookConfig_To_authentication_WebhookConfig(in, out, s)
}

func autoConvert_authentication_WebhookConfig_To_v1alpha1_WebhookConfig(in *authentication.WebhookConfig, out *v1alpha1.WebhookConfig, s conversion.Scope) error {
	return nil
}

// Convert_authentication_WebhookConfig_To_v1alpha1_WebhookConfig is an autogenerated conversion function.
func Convert_authentication_WebhookConfig_To_v1alpha1_WebhookConfig(in *authentication.WebhookConfig, out *v1alpha1.WebhookConfig, s conversion.Scope) error {
	return autoConvert_authentication_WebhookConfig_To_v1alpha1_WebhookConfig(in, out, s)
}

func autoConvert_v1alpha1_X509Config_To_authentication_X509Config(in *v1alpha1.X509Config, out *authentication.X509Config, s conversion.Scope) error {
	out.CABundle = *(*[]byte)(unsafe.Pointer(&in.CABundle))
	return nil
}

// Convert_v1alpha1_X509Config_To_authentication_X509Config is an autogenerated conversion function.
func Convert_v1alpha1_X509Config_To_authentication_X509Config(in *v1alpha1.X509Config, out *authentication.X509Config, s conversion.Scope) error {
	return autoConvert_v1alpha1_X509Config_To_authentication_X509Config(in, out, s)
}

func autoConvert_authentication_X509Config_To_v1alpha1_X509Config(in *authentication.X509Config, out *v1alpha1.X509Config, s conversion.Scope) error {
	out.CABundle = *(*[]byte)(unsafe.Pointer(&in.CABundle))
	return nil
}

// Convert_authentication_X509Config_To_v1alpha1_X509Config is an autogenerated conversion function.
func Convert_authentication_X509Config_To_v1alpha1_X509Config(in *authentication.X509Config, out *v1alpha1.X509Config, s conversion.Scope) error {
	return autoConvert_authentication_X509Config_To_v1alpha1_X509Config(in, out, s)
}
