/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "k8s.io/api/authentication/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAuthenticationConfigs implements AuthenticationConfigInterface
type FakeAuthenticationConfigs struct {
	Fake *FakeAuthenticationV1alpha1
}

var authenticationconfigsResource = schema.GroupVersionResource{Group: "authentication.k8s.io", Version: "v1alpha1", Resource: "authenticationconfigs"}

var authenticationconfigsKind = schema.GroupVersionKind{Group: "authentication.k8s.io", Version: "v1alpha1", Kind: "AuthenticationConfig"}

// Get takes name of the authenticationConfig, and returns the corresponding authenticationConfig object, and an error if there is any.
func (c *FakeAuthenticationConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.AuthenticationConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(authenticationconfigsResource, name), &v1alpha1.AuthenticationConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationConfig), err
}

// List takes label and field selectors, and returns the list of AuthenticationConfigs that match those selectors.
func (c *FakeAuthenticationConfigs) List(opts v1.ListOptions) (result *v1alpha1.AuthenticationConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(authenticationconfigsResource, authenticationconfigsKind, opts), &v1alpha1.AuthenticationConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AuthenticationConfigList{ListMeta: obj.(*v1alpha1.AuthenticationConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.AuthenticationConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested authenticationConfigs.
func (c *FakeAuthenticationConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(authenticationconfigsResource, opts))
}

// Create takes the representation of a authenticationConfig and creates it.  Returns the server's representation of the authenticationConfig, and an error, if there is any.
func (c *FakeAuthenticationConfigs) Create(authenticationConfig *v1alpha1.AuthenticationConfig) (result *v1alpha1.AuthenticationConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(authenticationconfigsResource, authenticationConfig), &v1alpha1.AuthenticationConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationConfig), err
}

// Update takes the representation of a authenticationConfig and updates it. Returns the server's representation of the authenticationConfig, and an error, if there is any.
func (c *FakeAuthenticationConfigs) Update(authenticationConfig *v1alpha1.AuthenticationConfig) (result *v1alpha1.AuthenticationConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(authenticationconfigsResource, authenticationConfig), &v1alpha1.AuthenticationConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAuthenticationConfigs) UpdateStatus(authenticationConfig *v1alpha1.AuthenticationConfig) (*v1alpha1.AuthenticationConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(authenticationconfigsResource, "status", authenticationConfig), &v1alpha1.AuthenticationConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationConfig), err
}

// Delete takes name of the authenticationConfig and deletes it. Returns an error if one occurs.
func (c *FakeAuthenticationConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(authenticationconfigsResource, name), &v1alpha1.AuthenticationConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuthenticationConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(authenticationconfigsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AuthenticationConfigList{})
	return err
}

// Patch applies the patch and returns the patched authenticationConfig.
func (c *FakeAuthenticationConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AuthenticationConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(authenticationconfigsResource, name, pt, data, subresources...), &v1alpha1.AuthenticationConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationConfig), err
}
