/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	rbacv1alpha1 "k8s.io/api/rbac/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ConditionalClusterRoleBindingLister helps list ConditionalClusterRoleBindings.
// All objects returned here must be treated as read-only.
type ConditionalClusterRoleBindingLister interface {
	// List lists all ConditionalClusterRoleBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rbacv1alpha1.ConditionalClusterRoleBinding, err error)
	// Get retrieves the ConditionalClusterRoleBinding from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*rbacv1alpha1.ConditionalClusterRoleBinding, error)
	ConditionalClusterRoleBindingListerExpansion
}

// conditionalClusterRoleBindingLister implements the ConditionalClusterRoleBindingLister interface.
type conditionalClusterRoleBindingLister struct {
	listers.ResourceIndexer[*rbacv1alpha1.ConditionalClusterRoleBinding]
}

// NewConditionalClusterRoleBindingLister returns a new ConditionalClusterRoleBindingLister.
func NewConditionalClusterRoleBindingLister(indexer cache.Indexer) ConditionalClusterRoleBindingLister {
	return &conditionalClusterRoleBindingLister{listers.New[*rbacv1alpha1.ConditionalClusterRoleBinding](indexer, rbacv1alpha1.Resource("conditionalclusterrolebinding"))}
}
