/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	rbacv1alpha1 "k8s.io/api/rbac/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	internal "k8s.io/client-go/applyconfigurations/internal"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ConditionalClusterRoleBindingApplyConfiguration represents a declarative configuration of the ConditionalClusterRoleBinding type for use
// with apply.
type ConditionalClusterRoleBindingApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	ClusterRoleName                  *string                       `json:"clusterRoleName,omitempty"`
	Variables                        []VariableApplyConfiguration  `json:"variables,omitempty"`
	Conditions                       []ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ConditionalClusterRoleBinding constructs a declarative configuration of the ConditionalClusterRoleBinding type for use with
// apply.
func ConditionalClusterRoleBinding(name string) *ConditionalClusterRoleBindingApplyConfiguration {
	b := &ConditionalClusterRoleBindingApplyConfiguration{}
	b.WithName(name)
	b.WithKind("ConditionalClusterRoleBinding")
	b.WithAPIVersion("rbac.authorization.k8s.io/v1alpha1")
	return b
}

// ExtractConditionalClusterRoleBinding extracts the applied configuration owned by fieldManager from
// conditionalClusterRoleBinding. If no managedFields are found in conditionalClusterRoleBinding for fieldManager, a
// ConditionalClusterRoleBindingApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// conditionalClusterRoleBinding must be a unmodified ConditionalClusterRoleBinding API object that was retrieved from the Kubernetes API.
// ExtractConditionalClusterRoleBinding provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
// Experimental!
func ExtractConditionalClusterRoleBinding(conditionalClusterRoleBinding *rbacv1alpha1.ConditionalClusterRoleBinding, fieldManager string) (*ConditionalClusterRoleBindingApplyConfiguration, error) {
	return extractConditionalClusterRoleBinding(conditionalClusterRoleBinding, fieldManager, "")
}

// ExtractConditionalClusterRoleBindingStatus is the same as ExtractConditionalClusterRoleBinding except
// that it extracts the status subresource applied configuration.
// Experimental!
func ExtractConditionalClusterRoleBindingStatus(conditionalClusterRoleBinding *rbacv1alpha1.ConditionalClusterRoleBinding, fieldManager string) (*ConditionalClusterRoleBindingApplyConfiguration, error) {
	return extractConditionalClusterRoleBinding(conditionalClusterRoleBinding, fieldManager, "status")
}

func extractConditionalClusterRoleBinding(conditionalClusterRoleBinding *rbacv1alpha1.ConditionalClusterRoleBinding, fieldManager string, subresource string) (*ConditionalClusterRoleBindingApplyConfiguration, error) {
	b := &ConditionalClusterRoleBindingApplyConfiguration{}
	err := managedfields.ExtractInto(conditionalClusterRoleBinding, internal.Parser().Type("io.k8s.api.rbac.v1alpha1.ConditionalClusterRoleBinding"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(conditionalClusterRoleBinding.Name)

	b.WithKind("ConditionalClusterRoleBinding")
	b.WithAPIVersion("rbac.authorization.k8s.io/v1alpha1")
	return b, nil
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithKind(value string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithAPIVersion(value string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithName(value string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithGenerateName(value string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithNamespace(value string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithUID(value types.UID) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithResourceVersion(value string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithGeneration(value int64) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithCreationTimestamp(value metav1.Time) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithLabels(entries map[string]string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithAnnotations(entries map[string]string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithFinalizers(values ...string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *ConditionalClusterRoleBindingApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithClusterRoleName sets the ClusterRoleName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRoleName field is set to the value of the last call.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithClusterRoleName(value string) *ConditionalClusterRoleBindingApplyConfiguration {
	b.ClusterRoleName = &value
	return b
}

// WithVariables adds the given value to the Variables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Variables field.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithVariables(values ...*VariableApplyConfiguration) *ConditionalClusterRoleBindingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVariables")
		}
		b.Variables = append(b.Variables, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ConditionalClusterRoleBindingApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *ConditionalClusterRoleBindingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *ConditionalClusterRoleBindingApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}
