/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	rbacv1alpha1 "k8s.io/api/rbac/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsrbacv1alpha1 "k8s.io/client-go/applyconfigurations/rbac/v1alpha1"
	gentype "k8s.io/client-go/gentype"
	scheme "k8s.io/client-go/kubernetes/scheme"
)

// ConditionalClusterRoleBindingsGetter has a method to return a ConditionalClusterRoleBindingInterface.
// A group's client should implement this interface.
type ConditionalClusterRoleBindingsGetter interface {
	ConditionalClusterRoleBindings() ConditionalClusterRoleBindingInterface
}

// ConditionalClusterRoleBindingInterface has methods to work with ConditionalClusterRoleBinding resources.
type ConditionalClusterRoleBindingInterface interface {
	Create(ctx context.Context, conditionalClusterRoleBinding *rbacv1alpha1.ConditionalClusterRoleBinding, opts v1.CreateOptions) (*rbacv1alpha1.ConditionalClusterRoleBinding, error)
	Update(ctx context.Context, conditionalClusterRoleBinding *rbacv1alpha1.ConditionalClusterRoleBinding, opts v1.UpdateOptions) (*rbacv1alpha1.ConditionalClusterRoleBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*rbacv1alpha1.ConditionalClusterRoleBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*rbacv1alpha1.ConditionalClusterRoleBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rbacv1alpha1.ConditionalClusterRoleBinding, err error)
	Apply(ctx context.Context, conditionalClusterRoleBinding *applyconfigurationsrbacv1alpha1.ConditionalClusterRoleBindingApplyConfiguration, opts v1.ApplyOptions) (result *rbacv1alpha1.ConditionalClusterRoleBinding, err error)
	ConditionalClusterRoleBindingExpansion
}

// conditionalClusterRoleBindings implements ConditionalClusterRoleBindingInterface
type conditionalClusterRoleBindings struct {
	*gentype.ClientWithListAndApply[*rbacv1alpha1.ConditionalClusterRoleBinding, *rbacv1alpha1.ConditionalClusterRoleBindingList, *applyconfigurationsrbacv1alpha1.ConditionalClusterRoleBindingApplyConfiguration]
}

// newConditionalClusterRoleBindings returns a ConditionalClusterRoleBindings
func newConditionalClusterRoleBindings(c *RbacV1alpha1Client) *conditionalClusterRoleBindings {
	return &conditionalClusterRoleBindings{
		gentype.NewClientWithListAndApply[*rbacv1alpha1.ConditionalClusterRoleBinding, *rbacv1alpha1.ConditionalClusterRoleBindingList, *applyconfigurationsrbacv1alpha1.ConditionalClusterRoleBindingApplyConfiguration](
			"conditionalclusterrolebindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *rbacv1alpha1.ConditionalClusterRoleBinding {
				return &rbacv1alpha1.ConditionalClusterRoleBinding{}
			},
			func() *rbacv1alpha1.ConditionalClusterRoleBindingList {
				return &rbacv1alpha1.ConditionalClusterRoleBindingList{}
			}),
	}
}
